import type { Metadata } from "next";
import { Martian_Mono } from "next/font/google";
import "./globals.css";
import Logo from "@/components/logo";

import { ThemeProvider } from "next-themes";

const martianMono = Martian_Mono({
  variable: "--font-martian-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Laike VS Dislaike",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${martianMono.variable}`}>
        <ThemeProvider>
          <Logo/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
